data = {
    'oui': {'question': "Travaillez-vous dans le millieu médical ?", 
            'oui': {'question': "Êtes vous médecin ?", 
                'oui': {'question': "Êtes vous médecin généraliste ?", 
                    'oui': {'question': "Vous êtes médecin généraliste !", 
                        'oui': None,
                        'non': None}, 
                    'non': {'question': "Êtes vous dans le millieu hospitalier ?", 
                        'oui': {'question': "Travaillez vous dans les services d'urgences ?", 
                            'oui': {'question': "Vous occupez vous des services de maternité ? ", 
                                'oui': {'question': "Êtes vous sage femme ?", 
                                    'oui': {'question': "Vous êtes sage femme !", 
                                        'oui': None,
                                        'non': None},
                                    'non': {'question': "Travaillez vous dans les services de soins intensif ?", 
                                        'oui': {'question': "Êtes vous cardiologue ?", 
                                            'oui': {'question': "Vous êtes cardiologue !", 
                                                'oui': None,
                                                'non': None},
                                            'non': {'question': "Êtes vous chirurgien ?", 
                                                'oui': {'question': "Vous êtes chirurgien !", 
                                                    'oui': None,
                                                    'non': None},
                                                'non': {'question': "Êtes vous infirmière ?", 
                                                    'oui': {'question': "Vous êtes infirmière !", 
                                                        'oui': None,
                                                        'non': None},
                                                    'non': {'question': "Travaillez vous avec des radios ?", 
                                                        'oui': {'question': "Vous êtes radiologue !", 
                                                            'oui': None,
                                                            'non': None},
                                                        'non': {'question': "Je ne sais pas !", 
                                                            'oui': None,
                                                            'non': None}}}}},
                                        'non': {'question': "Votre métier a t-il un rapport avec le coeur ?", 
                                            'oui': {'question': "Êtes vous chirurgien ?", 
                                                'oui': {'question': "Vous êtes chirurien !", 
                                                    'oui': None,
                                                    'non': None},
                                                'non': {'question': "Je ne peux pas vous aider, je suis navré !", 
                                                    'oui': None,
                                                    'non': None}},
                                            'non': {'question': "Vous êtes urgentiste !", 
                                                'oui': None,
                                                'non': None}}}},
                                'non': {'question': "Travaillez vous dans les services de soins intensif ?", 
                                        'oui': {'question': "Êtes vous cardiologue ?", 
                                            'oui': {'question': "Vous êtes cardiologue !", 
                                                'oui': None,
                                                'non': None},
                                            'non': {'question': "Êtes vous chirurgien ?", 
                                                'oui': {'question': "Vous êtes chirurgien !", 
                                                    'oui': None,
                                                    'non': None},
                                                'non': {'question': "Êtes vous infirmière ?", 
                                                    'oui': {'question': "Vous êtes infirmière !", 
                                                        'oui': None,
                                                        'non': None},
                                                    'non': {'question': "Travaillez vous avec des radios ?", 
                                                        'oui': {'question': "Vous êtes radiologue !", 
                                                            'oui': None,
                                                            'non': None},
                                                        'non': {'question': "Je ne sais pas !", 
                                                            'oui': None,
                                                            'non': None}}}}},
                                        'non': {'question': "Votre métier a t-il un rapport avec le coeur ?", 
                                            'oui': {'question': "Êtes vous chirurgien ?", 
                                                'oui': {'question': "Vous êtes chirurien !", 
                                                    'oui': None,
                                                    'non': None},
                                                'non': {'question': "Je ne peux pas vous aider, je suis navré !", 
                                                    'oui': None,
                                                    'non': None}},
                                            'non': {'question': "Vous êtes urgentiste !", 
                                                'oui': None,
                                                'non': None}}}},
                            'non': {'question': "Travaillez vous dans le millieu pharmacetique ?", 
                                'oui': {'question': "Faites vous des livraisons dans le millieu médical ?", 
                                    'oui': {'question': "Êtes vous livreur de produits pharmacetique ?", 
                                        'oui': {'question': "Vous êtes livreur de produits pharmacetique !", 
                                            'oui': None,
                                            'non': None},
                                        'non': {'question': "Êtes vous pharmacien ?", 
                                            'oui': {'question': "Vous êtes pharmacien !", 
                                                'oui': None,
                                                'non': None},
                                            'non': {'question': "Vous êtes technicien de laboratoire !", 
                                                'oui': None,
                                                'non': None}}},
                                    'non': {'question': "Êtes vous pharmacien ?", 
                                            'oui': {'question': "Vous êtes pharmacien !", 
                                                'oui': None,
                                                'non': None},
                                            'non': {'question': "Vous êtes technicien de laboratoire !", 
                                                'oui': None,
                                                'non': None}}},
                                'non': {'question': "Êtes vous médecin généraliste ?", 
                                    'oui': {'question': "Vous êtes médecin généraliste !", 
                                                'oui': None,
                                                'non': None},
                                    'non': {'question': "Travaillez vous dans la kinésithérapie ?", 
                                                'oui': {'question': "Vous êtes kiné !", 
                                                    'oui': None,
                                                    'non': None},
                                                'non': {'question': "Vous êtes psychologue !", 
                                                    'oui': None,
                                                    'non': None}}}}},
                        'non': {'question': "Travaillez vous dans le millieu pharmacetique ?", 
                                'oui': {'question': "Faites vous des livraisons dans le millieu médical ?", 
                                    'oui': {'question': "Êtes vous livreur de produits pharmacetique ?", 
                                        'oui': {'question': "Vous êtes livreur de produits pharmacetique !", 
                                            'oui': None,
                                            'non': None},
                                        'non': {'question': "Êtes vous pharmacien ?", 
                                            'oui': {'question': "Vous êtes pharmacien !", 
                                                'oui': None,
                                                'non': None},
                                            'non': {'question': "Vous êtes technicien de laboratoire !", 
                                                'oui': None,
                                                'non': None}}},
                                    'non': {'question': "Êtes vous pharmacien ?", 
                                            'oui': {'question': "Vous êtes pharmacien !", 
                                                'oui': None,
                                                'non': None},
                                            'non': {'question': "Vous êtes technicien de laboratoire !", 
                                                'oui': None,
                                                'non': None}}},
                                'non': {'question': "Êtes vous médecin généraliste ?", 
                                    'oui': {'question': "Vous êtes médecin généraliste !", 
                                                'oui': None,
                                                'non': None},
                                    'non': {'question': "Travaillez vous dans la kinésithérapie ?", 
                                                'oui': {'question': "Vous êtes kiné !", 
                                                    'oui': None,
                                                    'non': None},
                                                'non': {'question': "Vous êtes psychologue !", 
                                                    'oui': None,
                                                    'non': None}}}}}}, 
                'non': {'question': "Êtes vous dans le millieu hospitalier ?", 
                        'oui': {'question': "Travaillez vous dans les services d'urgences ?", 
                            'oui': {'question': "Vous occupez vous des services de maternité ? ", 
                                'oui': {'question': "Êtes vous sage femme ?", 
                                    'oui': {'question': "Vous êtes sage femme !", 
                                        'oui': None,
                                        'non': None},
                                    'non': {'question': "Travaillez vous dans les services de soins intensif ?", 
                                        'oui': {'question': "Êtes vous cardiologue ?", 
                                            'oui': {'question': "Vous êtes cardiologue !", 
                                                'oui': None,
                                                'non': None},
                                            'non': {'question': "Êtes vous chirurgien ?", 
                                                'oui': {'question': "Vous êtes chirurgien !", 
                                                    'oui': None,
                                                    'non': None},
                                                'non': {'question': "Êtes vous infirmière ?", 
                                                    'oui': {'question': "Vous êtes infirmière !", 
                                                        'oui': None,
                                                        'non': None},
                                                    'non': {'question': "Travaillez vous avec des radios ?", 
                                                        'oui': {'question': "Vous êtes radiologue !", 
                                                            'oui': None,
                                                            'non': None},
                                                        'non': {'question': "Je ne sais pas !", 
                                                            'oui': None,
                                                            'non': None}}}}},
                                        'non': {'question': "Votre métier a t-il un rapport avec le coeur ?", 
                                            'oui': {'question': "Êtes vous chirurgien ?", 
                                                'oui': {'question': "Vous êtes chirurien !", 
                                                    'oui': None,
                                                    'non': None},
                                                'non': {'question': "Je ne peux pas vous aider, je suis navré !", 
                                                    'oui': None,
                                                    'non': None}},
                                            'non': {'question': "Vous êtes urgentiste !", 
                                                'oui': None,
                                                'non': None}}}},
                                'non': {'question': "Travaillez vous dans les services de soins intensif ?", 
                                        'oui': {'question': "Êtes vous cardiologue ?", 
                                            'oui': {'question': "Vous êtes cardiologue !", 
                                                'oui': None,
                                                'non': None},
                                            'non': {'question': "Êtes vous chirurgien ?", 
                                                'oui': {'question': "Vous êtes chirurgien !", 
                                                    'oui': None,
                                                    'non': None},
                                                'non': {'question': "Êtes vous infirmière ?", 
                                                    'oui': {'question': "Vous êtes infirmière !", 
                                                        'oui': None,
                                                        'non': None},
                                                    'non': {'question': "Travaillez vous avec des radios ?", 
                                                        'oui': {'question': "Vous êtes radiologue !", 
                                                            'oui': None,
                                                            'non': None},
                                                        'non': {'question': "Je ne sais pas !", 
                                                            'oui': None,
                                                            'non': None}}}}},
                                        'non': {'question': "Votre métier a t-il un rapport avec le coeur ?", 
                                            'oui': {'question': "Êtes vous chirurgien ?", 
                                                'oui': {'question': "Vous êtes chirurien !", 
                                                    'oui': None,
                                                    'non': None},
                                                'non': {'question': "Je ne peux pas vous aider, je suis navré !", 
                                                    'oui': None,
                                                    'non': None}},
                                            'non': {'question': "Vous êtes urgentiste !", 
                                                'oui': None,
                                                'non': None}}}},
                            'non': {'question': "Travaillez vous dans le millieu pharmacetique ?", 
                                'oui': {'question': "Faites vous des livraisons dans le millieu médical ?", 
                                    'oui': {'question': "Êtes vous livreur de produits pharmacetique ?", 
                                        'oui': {'question': "Vous êtes livreur de produits pharmacetique !", 
                                            'oui': None,
                                            'non': None},
                                        'non': {'question': "Êtes vous pharmacien ?", 
                                            'oui': {'question': "Vous êtes pharmacien !", 
                                                'oui': None,
                                                'non': None},
                                            'non': {'question': "Vous êtes technicien de laboratoire !", 
                                                'oui': None,
                                                'non': None}}},
                                    'non': {'question': "Êtes vous pharmacien ?", 
                                            'oui': {'question': "Vous êtes pharmacien !", 
                                                'oui': None,
                                                'non': None},
                                            'non': {'question': "Vous êtes technicien de laboratoire !", 
                                                'oui': None,
                                                'non': None}}},
                                'non': {'question': "Êtes vous médecin généraliste ?", 
                                    'oui': {'question': "Vous êtes médecin généraliste !", 
                                                'oui': None,
                                                'non': None},
                                    'non': {'question': "Travaillez vous dans la kinésithérapie ?", 
                                                'oui': {'question': "Vous êtes kiné !", 
                                                    'oui': None,
                                                    'non': None},
                                                'non': {'question': "Vous êtes psychologue !", 
                                                    'oui': None,
                                                    'non': None}}}}},
                        'non': {'question': "Travaillez vous dans le millieu pharmacetique ?", 
                                'oui': {'question': "Faites vous des livraisons dans le millieu médical ?", 
                                    'oui': {'question': "Êtes vous livreur de produits pharmacetique ?", 
                                        'oui': {'question': "Vous êtes livreur de produits pharmacetique !", 
                                            'oui': None,
                                            'non': None},
                                        'non': {'question': "Êtes vous pharmacien ?", 
                                            'oui': {'question': "Vous êtes pharmacien !", 
                                                'oui': None,
                                                'non': None},
                                            'non': {'question': "Vous êtes technicien de laboratoire !", 
                                                'oui': None,
                                                'non': None}}},
                                    'non': {'question': "Êtes vous pharmacien ?", 
                                            'oui': {'question': "Vous êtes pharmacien !", 
                                                'oui': None,
                                                'non': None},
                                            'non': {'question': "Vous êtes technicien de laboratoire !", 
                                                'oui': None,
                                                'non': None}}},
                                'non': {'question': "Êtes vous médecin généraliste ?", 
                                    'oui': {'question': "Vous êtes médecin généraliste !", 
                                                'oui': None,
                                                'non': None},
                                    'non': {'question': "Travaillez vous dans la kinésithérapie ?", 
                                                'oui': {'question': "Vous êtes kiné !", 
                                                    'oui': None,
                                                    'non': None},
                                                'non': {'question': "Vous êtes psychologue !", 
                                                    'oui': None,
                                                    'non': None}}}}}}, 
            'non': {
                'question': "Travaillez-vous dans le domaine de l'informatique ?", 
                'oui': {
                    'question': "Êtes-vous développeur(se) ?", 
                    'oui': {
                        'question': "Quel est votre domaine de développement ?", 
                        'oui': {
                            'question': "Vous êtes développeur(se) spécialisé(e) en {{domaine}} !", 
                            'oui': None,
                            'non': None
                        },
                        'non': None
                    },
                    'non': {
                        'question': "Travaillez-vous dans le support informatique ?", 
                        'oui': {
                            'question': "Vous êtes technicien(ne) de support informatique !", 
                            'oui': None,
                            'non': None
                        },
                        'non': {
                            'question': "Travaillez-vous dans la sécurité informatique ?", 
                            'oui': {
                                'question': "Vous êtes expert(e) en sécurité informatique !", 
                                'oui': None,
                                'non': None
                            },
                            'non': {
                                'question': "Exercez-vous un autre métier dans le domaine de l'informatique ?", 
                                'oui': {
                                    'question': "Quel est votre métier ?", 
                                    'oui': {
                                        'question': "Vous êtes {{métier}} !", 
                                        'oui': None,
                                        'non': None
                                    },
                                    'non': None
                                },
                                'non': None
                            }
                        }
                    }
                }, 
                'non': {'question': "Êtes vous au chomage ?", 
                    'oui': {'question': "Vous êtes au chomage !", 
                        'oui': None, 
                        'non': None}, 
                    'non': {'question': "Êtes vous étudiant ?", 
                        'oui': {'question': "Vous êtes étudiant !", 
                            'oui': None, 
                            'non': None}, 
                        'non': {'question': "Je ne peux pas vous aider !", 
                            'oui': None, 
                            'non': None}}}
                            }},
    'non': {'question': "Êtes vous au chomage ?", 
            'oui': None, 
            'non': None}
}